<!DOCTYPE html>
<html lang="en">
    <?php _include('common/head'); ?>
    <body>
        <div id="wrapper">
            <?php _include('common/nav'); ?>
            <div id="page-wrapper">
                <?php _include('common/title'); ?>
                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-8">
                        <!-- /.panel -->
                        <?php _include('common/list'); ?>
                    </div>
                    <!-- /.col-lg-8 -->
                    <div class="col-lg-4">
                        <!-- /.panel -->
                        <?php _include('common/chat'); ?>
                        <!-- /.panel .chat-panel -->
                    </div>
                    <!-- /.col-lg-4 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="/statics/js/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/statics/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/statics/js/metisMenu.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="/statics/js/raphael.min.js"></script>
        <script src="/statics/js/morris.min.js"></script>
        <script src="/statics/data/morris-data.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/statics/js/sb-admin-2.js"></script>

    </body>

</html>
